### ISSUE TITLE
Is simple_jsonapi_client alive and maintained?

### ISSUE THREAD

**Issue by ms-ati** [amcaplan/simple_jsonapi_client#2]
Hi! Thanks for this library, it looks very useful.

@amcaplan can you clarify if this project is alive? Will issues and pull requests be responded to, or will they languish forever?

Why ask in advance? Because many of the JSON API clients in the ruby ecosystem, such as https://github.com/chingor13/json_api_client, appear to be dead.

**Comment by amcaplan** [comment]
@ms-ati thanks for asking! I consider this project very much alive, and I'll be happy to respond to issues and PRs as they come in.  Currently I don't have a strong need within my own work to iterate on the current functionality, but if there's a need in the community to add more, let's do it!
