### ISSUE TITLE
Feature Request: Ability to provide id on create

### ISSUE THREAD

**Issue by berkes** [amcaplan/simple_jsonapi_client#33]
I'm reading through the code but cannot find a way to provide an ID on `create()`[1]. When providing it as attribute, it becomes (no surprise!) an attribute. I'll gladly whip up a PR, but wanted to check how you see this, first.

Wanted:
```
id = SecureRandom.uuid
Foo.create(connection: connection, id: id, name: 'Bar')
```

```
POST "/foos"
{
  :data => {
    :type => "foos",
    :id => "ce2324d7-f63c-4b9b-8c91-15cce01a4fbd"
    :attributes => {
      :name => "Bar"
    },
    :relationships => {}
  }
}
```
Actual:
```
POST "/foos"
{
  :data => {
    :type => "foos",
    :attributes => {
      :name => "Bar",
      :id => "ce2324d7-f63c-4b9b-8c91-15cce01a4fbd"
    },
    :relationships => {}
  }
}
```
Would that be feasible? If so, how would you like a PR? I see three solutions:

1. Add `id: nil` to `create_request()` signature, falling back on current behaviour if not provided. The `create()` then needs to extract and remove the `:id` from its `opts` if provided. This removes the ability to have an attribute of `id`. But update does not support an id-attribute either. This would bring the create() in-line with update(), really.
2. add a `create()` to the instance variables. The path to create a resource with client-provided ID would then be Foo.new(id: SecureRandom.uuid, name: 'Bar').create` . Downside is that there are two ways to create resources that work differently.
3. Override the `create_request()` in my subclass, essentially not providing a PR :grin:. 

Would this be welcome? If so, how do you prefer this? Am I missing something obvious?

---
[1] Yes, I am aware of the implications of letting clients provide IDs. But the benefit of allowing for client-provided-ids is that greatly simplifies offline/async generation in clients. A client can generate resources, add the IDs and then treat them as if they come from the API eventhough they are not yet "synched".

**Comment by amcaplan** [comment]
Hi @berkes 👋 , thanks for a very thorough feature request! This is truly a model GitHub issue, I'm sure I'll point to it in the future as an example of How To Do It.

I appreciate that you consulted before implementing, and I would be delighted if you'd PR!

My first concern was whether this is supported by the JSON:API spec, but apparently [it is in the spec to provide a UUID](https://jsonapi.org/format/#crud-creating-client-ids), so I'm totally in favor of adding this.

I think the [`template` method](https://github.com/amcaplan/simple_jsonapi_client/blob/92841f5b31069d3f6fe5b6fbc6a247386e87b0ba/lib/simple_jsonapi_client/base.rb#L95-L103) should handle optionally adding an ID, so all we need is to add `id:` to the `create_request` signature and pass it to `template`, as we do with `update_request`.

Please note that I do care that new functionality is tested, so you might need to add a new model/endpoint to the spec app. I'm not sure whether `jsonapi-resources` supports user-generated IDs, so we may need some kind of custom controller, hopefully it won't be too much...

**Comment by berkes** [comment]
Thanks for the kind words. I'll whip up a PR and will take care to add it to the tests. I prefer to work TDD, so that I would've made tests anyway; i'll now just ensure to commit them as well. 

We're on some deadlines this week, so I'm not sure when I can pick this up, though: sorry about that.

**Comment by amcaplan** [comment]
No rush, this project has been around a while and survived without the feature so I assume it'll continue to be OK in the meantime. Whenever you're ready to PR I'll be delighted to have a look. And feel free to monkeypatch your own code until then!
